- id: cargo-fmt
  name: cargo fmt
  description: Format rust files with cargo fmt
  entry: cargo fmt
  language: system
  types: [rust]
  pass_filenames: false

- id: cargo-check
  name: cargo check
  description: Run cargo check for compilation errors
  entry: cargo check
  language: system
  types: [rust]
  pass_filenames: false

- id: cargo-clippy
  name: cargo clippy
  description: Run cargo clippy lint tool
  entry: cargo clippy
  language: system
  types: [rust]
  pass_filenames: false

- id: cargo-machete
  name: cargo machete
  description: Run cargo machete dependency checker
  entry: cargo machete
  language: system
  types: [rust]
  pass_filenames: false

# https://github.com/crate-ci/typos/blob/master/.pre-commit-hooks.yaml
- id: typos
  name: typos
  description: Source code spell checker, binary install
  language: python
  entry: typos
  args: [--write-changes, --force-exclude]
  types: [text]
  stages: [pre-commit, pre-merge-commit, pre-push, manual]

# https://github.com/EmbarkStudios/cargo-deny/blob/main/.pre-commit-hooks.yaml
- id: cargo-deny
  name: check Cargo dependencies
  description: check Cargo dependencies
  entry: cargo-deny
  language: rust
  types: [file, toml]
  files: Cargo\.(toml|lock)
  pass_filenames: false
  args: ["--all-features", "check"]
