# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/AliYmn/conventional-commits-check
    rev: v2.9.0
    hooks:
    -   id: conventional-commits-check
        stages: [commit-msg]
        args: ["--emoji-disabled"]

-   repo: local
    hooks:
    -   id: fmt
        name: fmt
        entry: cargo fmt --all --check
        language: system
        types: [rust]

    -   id: typos
        name: typos
        entry: typos
        language: system
        types: [rust]

    -   id: clippy
        name: clippy
        entry: cargo clippy --all-targets
        language: system
        types: [rust]

    -   id: deny
        name: deny
        entry: cargo deny check
        language: system
        types: [rust]

    -   id: machete
        name: machete
        entry: cargo machete
        language: system
        types: [rust]

    #-   id: semver
    #    name: semver
    #    entry: cargo semver-checks
    #    language: system
    #    types: [rust]
