[graph]
# cargo-deny is really only ever intended to run on the "normal" tier-1 targets
targets = [
    "x86_64-unknown-linux-gnu",
]
all-features = true

[advisories]
ignore = [
    "RUSTSEC-2023-0071",
    { id = "RUSTSEC-2023-0071", reason = "Marvin Attack: potential key recovery through timing sidechannels" },
]

[bans]
# Set 'multiple-versions' to warn for verbose reporting.
multiple-versions = "allow"
wildcards = "deny"
allow-wildcard-paths = false
deny = [
    { crate = "git2", use-instead = "gix" },
    { crate = "openssl", use-instead = "rustls" },
    { crate = "cmake", use-instead = "cc" },
]

[bans.workspace-dependencies]
duplicates = "deny"
include-path-dependencies = false
unused = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0",
    "MPL-2.0",
    "EPL-2.0",
    "ISC",
    "Zlib",
]
exceptions = [
    # Use exceptions for these as they only have a single user
    { allow = ["Unicode-DFS-2016"], crate = "unicode-ident" },
    { allow = ["OpenSSL"], crate = "ring" },
]

[[licenses.clarify]]
crate = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
