[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
env_logger = "0.11.5"
log = "0.4.22"
tokio = "1.41.0"
zenoh = "1.0.2"

[build-dependencies]
anyhow = "1.0.93"
vergen-git2 = { version = "1.0.1", features = ["build", "cargo", "rustc"] }
